=== MAnasKhan/BackEndAutomationFrameworkWithSpring/backend-functional-test/target/test-classes/jsonschemas/departmentSchema.json
{"definitions": {},
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "http://example.com/root.json",
  "type": "array",
  "title": "The Root Schema",
  "items": {
    "$id": "#/items",
    "type": "object",
    "title": "The Items Schema",
    "required": [
      "id",
      "name",
      "deptDescription",
      "categories"
    ],
    "properties": {
      "id": {
        "$id": "#/items/properties/id",
        "type": "integer",
        "title": "The Id Schema",
        "default": 0,
        "examples": [
          1
        ]
      },
      "name": {
        "$id": "#/items/properties/name",
        "type": "string",
        "title": "The Name Schema",
        "default": "",
        "examples": [
          "Accesories"
        ],
        "pattern": "^(.*)$"
      },
      "deptDescription": {
        "$id": "#/items/properties/deptDescription",
        "type": "string",
        "title": "The Deptdescription Schema",
        "default": "",
        "examples": [
          "access"
        ],
        "pattern": "^(.*)$"
      },
      "categories": {
        "$id": "#/items/properties/categories",
        "type": [
          "array",
          "null"
        ],
        "title": "The Categories Schema",
        "default": null,
        "items": {
          "$id": "#/items/properties/categories/items",
          "type": "object",
          "title": "The Items Schema",
          "required": [
            "id",
            "name",
            "categoryDescription",
            "categories",
            "image_url"
          ],
          "properties": {
            "id": {
              "$id": "#/items/properties/categories/items/properties/id",
              "type": "integer",
              "title": "The Id Schema",
              "default": 0,
              "examples": [
                1
              ]
            },
            "name": {
              "$id": "#/items/properties/categories/items/properties/name",
              "type": "string",
              "title": "The Name Schema",
              "default": "",
              "examples": [
                "Shoes"
              ],
              "pattern": "^(.*)$"
            },
            "categoryDescription": {
              "$id": "#/items/properties/categories/items/properties/categoryDescription",
              "type": "string",
              "title": "The Categorydescription Schema",
              "default": "",
              "examples": [
                "Shoes"
              ],
              "pattern": "^(.*)$"
            },
            "categories": {
              "$id": "#/items/properties/categories/items/properties/categories",
              "type": [
                "array",
                "null"
              ],
              "title": "The Categories Schema",
              "default": null,
              "items": {
                "$id": "#/items/properties/categories/items/properties/categories/items",
                "type": "object",
                "title": "The Items Schema",
                "required": [
                  "id",
                  "name",
                  "categoryDescription",
                  "categories",
                  "image_url"
                ],
                "properties": {
                  "id": {
                    "$id": "#/items/properties/categories/items/properties/categories/items/properties/id",
                    "type": "integer",
                    "title": "The Id Schema",
                    "default": 0,
                    "examples": [
                      24
                    ]
                  },
                  "name": {
                    "$id": "#/items/properties/categories/items/properties/categories/items/properties/name",
                    "type": "string",
                    "title": "The Name Schema",
                    "default": "",
                    "examples": [
                      "anasbhai"
                    ],
                    "pattern": "^(.*)$"
                  },
                  "categoryDescription": {
                    "$id": "#/items/properties/categories/items/properties/categories/items/properties/categoryDescription",
                    "type": "string",
                    "title": "The Categorydescription Schema",
                    "default": "",
                    "examples": [
                      "jawad1"
                    ],
                    "pattern": "^(.*)$"
                  },
                  "categories": {
                    "$id": "#/items/properties/categories/items/properties/categories/items/properties/categories",
                    "type": [
                      "array",
                      "null"
                    ],
                    "title": "The Categories Schema",
                    "default": null,
                    "examples": [
                      null
                    ]
                  },
                  "image_url": {
                    "$id": "#/items/properties/categories/items/properties/categories/items/properties/image_url",
                    "type": [
                      "string",
                      "null"
                    ],
                    "title": "The Image_url Schema",
                    "default": null,
                    "examples": [
                      null
                    ]
                  }
                }
              }
            },
            "image_url": {
              "$id": "#/items/properties/categories/items/properties/image_url",
              "type": [
                "string",
                "null"
              ],
              "title": "The Image_url Schema",
              "default": "",
              "examples": [
                "googl.com"
              ],
              "pattern": "^(.*)$"
            }
          }
        }
      }
    }
  }
}

=== MAnasKhan/BackEndAutomationFrameworkWithSpring/backend-functional-test/target/test-classes/requests/temp.json
[
  {
    "id": 1,
    "name": "Accesories",
    "deptDescription": "access",
    "categories": [
      {
        "id": 6,
        "name": "cat",
        "categoryDescription": "cat shoes",
        "categories": null,
        "image_url": "googl.com"
      },
      {
        "id": 5,
        "name": "puma",
        "categoryDescription": "puma shoes",
        "categories": null,
        "image_url": "googl.com"
      },
      {
        "id": 1,
        "name": "Shoes",
        "categoryDescription": "Shoes",
        "categories": [
          {
            "id": 24,
            "name": "anasbhai",
            "categoryDescription": "jawad1",
            "categories": null,
            "image_url": null
          },
          {
            "id": 3,
            "name": "nike",
            "categoryDescription": "joggers",
            "categories": [
              {
                "id": 4,
                "name": "nike jogger",
                "categoryDescription": "nike joggers",
                "categories": null,
                "image_url": "googl.com"
              }
            ],
            "image_url": "googl.com"
          },
          {
            "id": 21,
            "name": "car",
            "categoryDescription": "car des",
            "categories": null,
            "image_url": null
          },
          {
            "id": 23,
            "name": "jawad",
            "categoryDescription": "jawad",
            "categories": null,
            "image_url": null
          },
          {
            "id": 2,
            "name": "Oxfords",
            "categoryDescription": "oxfords",
            "categories": null,
            "image_url": "googl.com"
          },
          {
            "id": 25,
            "name": "anasbhai",
            "categoryDescription": "jawad1",
            "categories": null,
            "image_url": "G:\\OneStopShop\\1stopshopbackend\\service\\business-admin-service//images//cstore.onestopshop.com//1//614e1e9a-6cc2-41be-a114-d54ab4855a62_intellij language change.png"
          },
          {
            "id": 20,
            "name": "car",
            "categoryDescription": "car des",
            "categories": null,
            "image_url": null
          },
          {
            "id": 22,
            "name": "jawad",
            "categoryDescription": "jawad",
            "categories": null,
            "image_url": null
          }
        ],
        "image_url": "googl.com"
      }
    ]
  },
  {
    "id": 2,
    "name": "Mobiles",
    "deptDescription": "mobiles",
    "categories": [
      {
        "id": 9,
        "name": "Apple Airpods",
        "categoryDescription": "Apple Airpod",
        "categories": null,
        "image_url": "googl.com"
      },
      {
        "id": 7,
        "name": "Apple",
        "categoryDescription": "Apple Phones",
        "categories": [
          {
            "id": 8,
            "name": "Iphone X",
            "categoryDescription": "Apple New Model",
            "categories": null,
            "image_url": "googl.com"
          }
        ],
        "image_url": "googl.com"
      }
    ]
  },
  {
    "id": 3,
    "name": "Electric Appliance",
    "deptDescription": "Electronic Appliance",
    "categories": [
      {
        "id": 10,
        "name": "Washing Machine",
        "categoryDescription": "Washing Machine",
        "categories": [
          {
            "id": 11,
            "name": "Automatic Machine",
            "categoryDescription": "Automatic Washing Machine",
            "categories": [
              {
                "id": 12,
                "name": "Manual Machine",
                "categoryDescription": "Manual Machine",
                "categories": [
                  {
                    "id": 13,
                    "name": "Manual Machine Without Spinner",
                    "categoryDescription": "Manual Machine Without Spinner",
                    "categories": null,
                    "image_url": "googl.com"
                  },
                  {
                    "id": 14,
                    "name": "Manual Machine With Spinner",
                    "categoryDescription": "Manual Machine With Spinner",
                    "categories": [
                      {
                        "id": 15,
                        "name": "Manual Machine With 1- Spinner",
                        "categoryDescription": "Manual Machine With 1- Spinner14",
                        "categories": null,
                        "image_url": "googl.com"
                      },
                      {
                        "id": 16,
                        "name": "Manual Machine With 1- Spinner",
                        "categoryDescription": "Manual Machine With 1- Spinner",
                        "categories": null,
                        "image_url": null
                      }
                    ],
                    "image_url": "googl.com"
                  }
                ],
                "image_url": "googl.com"
              }
            ],
            "image_url": "googl.com"
          }
        ],
        "image_url": "googl.com"
      }
    ]
  }
]
